### ISSUE TITLE
Cannot import random password

### ISSUE THREAD

**Issue by DavidGiles** [pulumi/pulumi-random#160]
(this is from https://stackoverflow.com/questions/66781327/how-can-i-import-existing-password-into-pulumi, which at the time of writing has no suggested answers)

I am trying to import an existing stack into Pulumi, in particular I want to import an existing password, but have Pulumi generate that password for any future stacks.

As per https://www.pulumi.com/docs/reference/pkg/random/randompassword/#import I am running `pulumi import random:index/randomPassword:RandomPassword password Password123!`

## Expected behavior
The code for adding this password into the Pulumi application is displayed in the console, and the existing value is then available to use within the current stack.

## Current behavior
An error is returned: `random:index/randomPassword:RandomPassword resource 'password' has a problem: Required attribute is not set. Examine values at 'RandomPassword.Length'`

## Steps to reproduce

In a blank folder run:

1. `pulumi new azure-python`
2. `pulumi plugin install resource random 3.1.1`
3. `pulumi import random:index/randomPassword:RandomPassword password Password123!`

## Context (Environment)
This was actually for a training exercise I was writing which now works around this by setting the existing password as a secret and then requiring new stacks to have the password manually generated by the deployer.

It's not clear to me if the docs need updating (to have either a working command, or to not suggest that this is possible) or if this should work that a change is needed in the code.

**Comment by anuraaga** [comment]
Ran into this myself - FWIW, this does work on Terraform so I guess it's supposed to work here too but there seems to be a bridging issue.

**Comment by Iced-Sun** [comment]
Any update on this?

**Comment by leftbin-swarup** [comment]
I am running into the same exact problem with importing RandomString as well.

**Comment by florianrusch-cluetec** [comment]
I think the problem will be fixed by solving the overall issue https://github.com/pulumi/pulumi/issues/7160

**Comment by Frassle** [comment]
Sadly https://github.com/pulumi/pulumi/issues/7160 won't fix this issue. We're hitting a limitation that terraform can import these resources using its [`Importer` system](https://www.terraform.io/plugin/sdkv2/resources/import#importer-state-function).

Pulumi expects to be able to Read then Check a resource to import it. While our Read logic can call into the terraform import system it's import system doesn't fill in the "length" property. Because "length" is a required input when we call Check after getting the result back from Read it fails because "length" isn't there.

I think the easiest way to fix this would be to fix the [terraform importer](https://github.com/hashicorp/terraform-provider-random/blob/master/internal/provider/string.go#L205) to just set length then everything should just work

**Comment by AaronFriel** [comment]
@t0yv0 can you check if this is fixed after we update to TLS v4?

**Comment by Bakrog** [comment]
I still face this problem with current versions.

**Comment by t0yv0** [comment]
Thank you for your patience with us on figuring this out. I'm still a little confused by this issue but I gave it a try just now. We now have the latest release (4.11.1), and I now get this new error message:

```
    error: Preview failed: Cannot extract ID from "random_password" resource state: ID cannot be empty
```

The message is not very unhelpful. However looking at the help for `pulumi import --help` this does not seem to be the right argument set for import:

```
If using the command line args directly, the type, name, id and optional flags
must be provided.  For example:

    pulumi import 'aws:iam/user:User' name id
```

So I have tried this instead. I provisioned a stack with `pulumi up`:

```
name: test-random-1
runtime: yaml
description: A minimal Pulumi YAML program
resources:
  pw1:
    type: random:RandomPassword
    properties:
      length: 1
```

Now within the same folder I can find out the name (pw1 from the program), and ID (happens to be "none" from `pulumi stack export`), and I can run the import:


```
$ pulumi import random:index/randomPassword:RandomPassword pw1 none                                                                                                              
```

This now succeeds but the output is a bit underwhelming:

```
Please copy the following code into your Pulumi application. Not doing so
will cause Pulumi to report that an update will happen on the next update command.

Please note that the imported resources are marked as protected. To destroy them
you will need to remove the `protect` option and run `pulumi update` *before*
the destroy will take effect.

resources:
  pw1:
    type: random:RandomPassword
    properties:
      length: 1
    options:
      protect: true
```

From the [Import Docs](https://www.pulumi.com/docs/guides/adopting/import/) it seems that import is about harvesting the state of a resource existing in the cloud and bringing it back under Pulumi management so it now appears in the state file. This does not seem to do anything helpful with RandomPassword currently because it has no state in the cloud per se, and only in the state file?

Perhaps stepping back a bit, what is the problem that `pulumi import` needs to solve here? 

If I think of the problem of having an existing Pulumi password in stack X and having to use it in stack Y, I think perhaps of the [Stack References](https://www.pulumi.com/learn/building-with-pulumi/stack-references/) feature that could do it.

**Comment by t0yv0** [comment]
Is the scenario to import a Terraform-provisioned password into Pulumi?

**Comment by jacobfoard** [comment]
> Is the scenario to import a Terraform-provisioned password into Pulumi?

That was the reason I originally started following this issue. When we migrated to Pulumi I wasn't able to bring some "secrets" over without manually editing the state file.

**Comment by t0yv0** [comment]
Thanks for clarifying @jacobfoard !

We have some docs on bringing resources over from Terraform to Pulumi, confusingly they do not involve the `pulumi import` command:

https://www.pulumi.com/docs/guides/adopting/from_terraform/#importing-resources

**Comment by t0yv0** [comment]
Doing a bit more digging, it appears that Terraform supports this behavior also for import:

https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password#import

It makes sense that the expectation is that Pulumi will behave similarly. This still doesn't work at the moment but I will have a closer look next week and circle back here.

**Comment by t0yv0** [comment]
It appears it's working in v4.12.0! Please let us know if there's any issues!
